version: '3'

services:
  app:
    container_name: tech-test-app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    entrypoint: "/etc/entrypoint.sh"
    volumes:
      - ./:/var/www/html
    links:
      - mongo
    ports:
      - 80:8080

  mongo:
    container_name: tech-test-mongo
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - tech-test-mongodata:/data/db

volumes:
  tech-test-mongodata:
